version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finops-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/init/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql

volumes:
  pgdata:
