global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "airflow"
    metrics_path: /metrics
    static_configs:
      - targets: ["airflow:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['finops-app:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9112']

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]