name: Docs Update → GitBook

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  docs-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli

      - name: Build Docs
        run: gitbook build docs/ ./_book

      - name: Sync to GitBook
        env:
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
        run: |
          curl -X POST "https://api.gitbook.com/v1/spaces/$GITBOOK_SPACE_ID/content/import" \
            -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
            -F "content=@./_book"
