name: Docs Update → GitBook

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  docs-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install HonKit
        run: npm install -g honkit

      - name: Build Docs
        run: honkit build ./docs ./_book