name: Docs Check

on:
  pull_request:
    paths:
      - "docs/**"

jobs:
  docs-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: "docs"

      - name: Validate Mermaid/PlantUML
        run: |
          npm install -g @mermaid-js/mermaid-cli
          find docs -name "*.md" -exec mmdc -i {} -o /tmp/out.svg \;
